import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Carousel from "../components/carousels/carousel";
import Card3 from "<negocio>/components/cards/card3";
import CarouselOfertas from "<negocio>/components/carousels/carouselOfertas";
import Contact from "<negocio>/components/contact";
import { salud } from "../components/items/salud";
import { mensajes } from "../components/items/mensajes";
import { ofertas } from "../components/items/ofertas";
import { bebe } from "../components/items/bebe";
import SectionPlus from "../components/sectionPlus";
import { Typography, theme } from "antd";
const { Title } = Typography;
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { token } = theme.useToken();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Carousel />
        <Card3 title={""} data={mensajes} limite={3} />
        <CarouselOfertas />
        <Card3 title={"Bebes"} data={bebe} limite={1} />
        <Card3 title={"Salud"} data={salud} limite={1} />
        <SectionPlus />
        <Contact />
      </>
    </>
  );
}
